[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.clean-site]
command = "npm"
args = ["run", "clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.build-wasm]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown"]

[tasks.wasm-bindgen]
command = "wasm-bindgen"
args = ["--no-typescript", "--target", "web",  "--out-dir", "./package/release/", "--out-name", "dsa", "./target/wasm32-unknown-unknown/release/dsa.wasm"]
dependencies = ["build-wasm"]

[tasks.ensure-dirs]
command = "mkdir"
args = ["-p", "./package/release/assets/"]

[tasks.copy-wasm-fonts]
command = "cp"
args = ["-R", "assets/fonts", "./package/release/assets"]
dependencies = ["ensure-dirs"]

[tasks.build-site]
command = "npm"
args = ["run", "build", "--prefix", "web/"]

[tasks.run-server]
command = "cargo"
args = ["server", "--path", "./package/release", "--open"]
dependencies = ["wasm-bindgen", "copy-wasm-fonts"]

[tasks.run-browser]
dependencies = ["build-site", "run-server"]

[tasks.clean-build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.clean-test]
dependencies = ["clean", "test"]



[tasks.my-flow]
dependencies = [
    "format",
    "build",
    "test"
]