[env]
CARGO_PROFILE = "release"
CARGO_BUILD = "cargo build --release --target wasm32-unknown-unknown"
WASM_BUILD = "wasm-bindgen --no-typescript --target web --out-dir ./package/wasm/ --out-name dsa ./target/wasm32-unknown-unknown/release/dsa.wasm"

[env.development]
CARGO_PROFILE = "dev"
CARGO_BUILD = "cargo build --profile dev --target wasm32-unknown-unknown"
WASM_BUILD = "wasm-bindgen --no-typescript --target web --out-dir ./package/wasm/ --out-name dsa ./target/wasm32-unknown-unknown/debug/dsa.wasm"

[tasks.npm-install]
private = true
command = "npm"
args = ["install", "--prefix", "web"]

[tasks.clean-site]
private = true
command = "npm"
args = ["run", "clean"]

[tasks.build]
private = true
command = "cargo"
args = ["build"]

[tasks.build-wasm]
private = true
script = '''${CARGO_BUILD}'''

[tasks.wasm-bindgen]
private = true
script = '''${WASM_BUILD}'''
dependencies = ["build-wasm"]

[tasks.ensure-dirs]
private = true
command = "mkdir"
args = ["-p", "./package/release/assets/"]

[tasks.copy-wasm-fonts]
private = true
command = "cp"
args = ["-R", "assets/fonts", "./package/release/assets"]
dependencies = ["ensure-dirs"]

[tasks.build-site]
private = true
command = "npm"
args = ["run", "build", "--prefix", "web/"]
dependencies = ["npm-install"]

[tasks.clean-build]
private = true
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
private = true
command = "cargo"
args = ["test"]

# following are main tasks
[tasks.clean-test]
dependencies = ["clean", "test"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build-wasm-module]
dependencies = ["wasm-bindgen", "copy-wasm-fonts"]

[tasks.build-all]
dependencies = ["build-wasm-module", "build-site"]

[tasks.run]
command = "cargo"
args = ["server", "--path", "./package/release", "--open"]
dependencies = ["build-all"]

[tasks.run-dev]
command = "npm"
args = ["run", "dev", "--prefix", "web/"]
dependencies = ["build-all"]
