fns:
  - &server_fn |
      def handle_event(context):
        log("hello server")

  - &client_fn |
      def handle_event(context):
        log("hello client")

graph_defn:
  name: "test graph"
  nodes:
    - name: server
      fn: *server_fn
      attrs:
        tick: 5s
        icon: https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/main/dist/Database/Aurora.png

    - name: client1
      fn: *client_fn
      attrs:
        ticks: 10s
        icon: https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/main/dist/Containers/EKSAnywhere.png

    - name: client2
      fn: *client_fn
      attrs:
        icon: https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/main/dist/Compute/Batch.png

  allowed_connections:
    server: [client1, client2]
  graph:
    server: [client1, client2]
  graph_attrs:
      title: "A Sample Graph!"
      background: [0.1, 0.1, 0.1, 1.]
      connection_color: [0., 0.9, 0.9, 1.]
      text_color: [0.5, 0.5, 0.5, 1.0]
