fns:
  - &server_fn |
    log("hello from another world!")
    
  - &client_fn |

graph_defn: 
  graph:
    - name: server
      node_type: server
      links: [client1, client2]
    - name: client1
      node_type: client
      links: []
    - name: client2
      node_type: client
      links: []
  graph_attrs:
    background: "#D3D3D3"
    connection_color: "#000000"
    text_color: "#000000"
    title: some graph
  node_types:
    - id: server
      name: server
      params:
        - name: someparam
          type: Bool
          default: false
      attrs:
        tick: 5
        icon: https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/main/dist/Database/Aurora.png
    - name: client
      id: client
      params:
        - name: someint
          type: Integer
          default: 0
          min: 0
          max: 10
        - name: somefloat
          type: Float
          default: 0
          min: 0
          max: 10
      attrs:
        ticks: 10
        icon: https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/main/dist/Containers/EKSAnywhere.png

