name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install npm
      run: apt update && apt install nodejs
    - name: add wasm32 target
      run: rustup target add wasm32-unknown-unknown
    - name: install wasm32-bindgen-cli
      run: cargo install wasm32-bindgen-cli
    - name: Install cargo make
      run: cargo install --force cargo-make
    - name: Build everything
      run: cargo make build-all
